### ISSUE TITLE
Error sending invoice: HTTP error requesting POST (url_here) 504 Gateway Timeout; msg: '' Retry in 50s.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna-triage#100]
Lots of providers receiving this error over on the public Discord. Few has reported their daemon being unresponsive to `golemsp status` or other commands. Restarting fixes the issue temporarily and then it comes back again later.

![image](https://user-images.githubusercontent.com/33448819/112759439-44db9c00-8ff3-11eb-88d9-754db152e979.png)

**Comment by cryptobench** [comment]
Not sure if its related to [#1168](https://github.com/golemfactory/yagna/issues/1168)

**Comment by tworec** [comment]
We need to have full log from provider which was spawned with below command
```
YA_CORE_LOG=debug,ya_runtime_api=info,ya_runtime_vm=info,ya_payment=trace golemsp run --payment-network mainnet --subnet public-beta
```

Until logs are attached we cannot investigate it.

**Comment by tworec** [comment]
@cryptobench ^^

**Comment by cryptobench** [comment]
I've asked in the Discord and are awaiting logs being sent.

**Comment by cryptobench** [comment]
I've been getting a good amount of debug logs after i've requested it when users has reported this error. One thing i'm wondering about though, is that is it possible this error might not be reported when running DEBUG? I have **never** seen it in the DEBUG logs from users.

**Comment by maaktweluit** [comment]
@cryptobench there was a bug in the debug command, i have edited @tworec 's message..
Please ask the users to make debug logs again

We suspect this COULD be fixed by the market broadcast fixes ( ETA Tuesday in RC-4 ):
- https://github.com/golemfactory/yagna/issues/1201
- https://github.com/golemfactory/yagna/issues/1205

**Comment by cryptobench** [comment]
Okidoki, i'll update the users with the new command :-)

**Comment by tworec** [comment]
@cryptobench have you seen this error being reported lately?

**Comment by cryptobench** [comment]
> @cryptobench have you seen this error being reported lately?

Yes, very recently 
![image](https://user-images.githubusercontent.com/33448819/115293132-3e09fa00-a157-11eb-8717-4ea50cf73055.png)

The issue is that I have never seen the error when people are running DEBUG logging? Could it be that some of the args aren't right in the DEBUG log command? Can you give me a command you'd like the providers to try and run?

Is this still sufficient?

`YA_CORE_LOG=debug,ya_runtime_api=info,ya_runtime_vm=info,ya_payment=trace golemsp run --payment-network mainnet --subnet public-beta`

**Comment by maaktweluit** [comment]
yes, this is still valid to run yagna-core in trace ( and golemsp and ya-provider normally )

**Comment by cryptobench** [comment]
[ya-provider_rCURRENT (1) 5.log](https://github.com/golemfactory/yagna/files/6375854/ya-provider_rCURRENT.1.5.log)
[yagna_rCURRENT 4.log](https://github.com/golemfactory/yagna/files/6375857/yagna_rCURRENT.4.log)

**Comment by cryptobench** [comment]
[ya-provider_rCURRENT 20210425.log](https://github.com/golemfactory/yagna-triage/files/6375872/ya-provider_rCURRENT.20210425.log)
[yagna_rCURRENT 20210425.log](https://github.com/golemfactory/yagna-triage/files/6375873/yagna_rCURRENT.20210425.log)

**Comment by maaktweluit** [comment]
Thanks for the logs, they are of great value!

Findings:
- 504 (in this case) means the requestor does not reply in time to the `SendInvoice` message
- the `invoice/send` rest call is called again
- `yagna` is not ready for this, so returns a server error: code 500

i have noticed a similar issue with the 504 when accepting an invoice.

Will discuss this with the team tomorrow and start preparing a fix.

**Comment by cryptobench** [comment]
Lovely great to hear, thanks for checking them out.

In case you need more examples, here's one:

DEBUG logs running 0.7.0-rc2 from a provider on Discord. They contain this error.

[0.7.0-rc2.logs.zip](https://github.com/golemfactory/yagna/files/6397218/0.7.0-rc2.logs.zip)

**Comment by cryptobench** [comment]
### Payment bug does still appear to be common on the network.


Payment bug from Discord user 1
[504.log](https://github.com/golemfactory/yagna-triage/files/6466638/504.log)
[504provider.log](https://github.com/golemfactory/yagna-triage/files/6466639/504provider.log)

Payment bug from Discord user 2
[504yaprovider2.log](https://github.com/golemfactory/yagna-triage/files/6466672/504yaprovider2.log)
[504provider2yagna.log](https://github.com/golemfactory/yagna-triage/files/6466673/504provider2yagna.log)

I see that 504 is mentioned in the log still, so that's why i'm uploading them here. Let me know if you need a new issue to track it on instead.

**Comment by tworec** [comment]
https://github.com/golemfactory/yagna/pull/1293 shold fix this issue. It was not yet released. It will be released within 0.6.6 release this week (hopefully)

**Comment by cryptobench** [comment]
Providers on 0.6.7 is still receiving this message:
`504 Gateway Timeout; msg: 'Timeout sending DebitNote to remote Node.' Final debit note will be resent after 50s.`
and they're noticing payments are still missing from their wallet

[yagna_rCURRENT (1).log.gz](https://github.com/golemfactory/yagna-triage/files/6538502/yagna_rCURRENT.1.log.gz)
[ya-provider_rCURRENT (2).log.gz](https://github.com/golemfactory/yagna-triage/files/6538503/ya-provider_rCURRENT.2.log.gz)

**Comment by maaktweluit** [comment]
@cryptobench i have checked the logs and the debit note that caused the 504 was re-send and accepted:
```
[2021-05-21T19:21:18Z INFO  ya_payment::service::public] Node [0xdbbce9de66001b6826299894a1984828e26fc3e2] accepted DebitNote [74f12f93-b0a9-4404-ab41-4d42da14f7a9].
```

It also seems the requestor cancelled the work:
```
[2021-05-21T19:21:06Z INFO  ya_provider::market::provider_market] Agreement [c3d3ea2e2201db4ce213681f5d4f3de19bf23386de6497b1e8d45382b2080a9b] terminated by Requestor. Reason: Work cancelled
```

This could be the reason the invoice is never accepted, when requestor is canceled ( not gracefull ) there is no time to accept the invoice.

**Comment by tworec** [comment]
@cryptobench does that close the issue for you?
