### ISSUE TITLE
Providers will probably not respond to tasks which expire sooner than 5 min or later than 30 min

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna-triage#109]
Yapapi still prints out:
`WARNING yapapi.summary] Expiration time for your tasks is set to 119 min 59 sec from now. Providers will probably not respond to tasks which expire sooner than 5 min or later than 30 min, counting from the moment they get your demand. Use the `timeout` parameter to `Executor()` to adjust the timeout. `
when requesting a task on the network. AFAIK the limit has been raised from 30 minutes to 3 hours.

**Comment by jiivan** [comment]
https://github.com/golemfactory/yagna/blob/830288196bff943f8819a633041acf55fe78fbf5/agent/provider/src/market/negotiator/factory.rs#L18-L29

Current values in master, 0.6.7-beta.1 and pre-rel-0.7.0 are: 5 minutes to 3 hours. (unless modified by env)

**Comment by tworec** [comment]
Using debit note keep alive feature is needed. If one does not use it, the upper bound is 30mins.

https://github.com/golemfactory/yagna/blob/830288196bff943f8819a633041acf55fe78fbf5/agent/provider/src/market/negotiator/factory.rs#L25-L26
