### ISSUE TITLE
payments - switching to ngnt keeps hanging payments in previous driver

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#11]
Asignee: maaktweluit, wiezzel
Reporter: jmuszyn

providers had missing payments, probably related to switching drivers

**Comment by maaktweluit** [comment]
This should be tested again:
- requestors no longer needs to restart to enable erc20 ( 0.6.0 )
- retries are implemented in zksync ( 0.6.1 = beta.1 )
