### ISSUE TITLE
munin checks didn't find zkSync proxy is not working

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-triage#118]
the zkSync rinkeby payments didn't go through (during requestor testing session today) -> it seems weird that testnet checkers didn't catch it up

**Comment by etam** [comment]
1) Munin has no checks for zksync proxy yet. https://github.com/golemfactory/golem-internal/issues/278
2) We have a mainnet AR running once a day that uses proxy. It went fine today.

**Comment by mateuszsrebrny** [comment]
ok, closing this as a dup of golemfactory/golem-internal#278
