### ISSUE TITLE
Task not completing after failure

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#123]
Name: Gert-Jan
OS+lang+version (if applicable): Mac-OS
Title: Task not completing after failure
!!! attach `blender-yapapi.log`, zipped data-dir !!!

```
    [2021-06-10 12:32:37,805 INFO yapapi.summary] Task started on provider 'descriptive-beast', task data: 10
 ```

    AND upload full logs here:
[GolemFactory.yagna.zip](https://github.com/golemfactory/yagna-triage/files/6631056/GolemFactory.yagna.zip)
[blender-yapapi-2021-06-10_12.32.10.log](https://github.com/golemfactory/yagna-triage/files/6631057/blender-yapapi-2021-06-10_12.32.10.log)
[blender-yapapi-2021-06-10_12.25.50.log](https://github.com/golemfactory/yagna-triage/files/6631058/blender-yapapi-2021-06-10_12.25.50.log)

**Comment by mfranciszkiewicz** [comment]
@maaktweluit Could you please clarify this issue - was the activity failure not reported properly or somehow that status got lost?

**Comment by maaktweluit** [comment]
@mfranciszkiewicz for sure!

in short: the task did not complete in a decent time ( 8 mins ).

Longer version:
While investigating why the task was stuck i noticed there where 2 "jobs" that failed, but they seem to be handled correctly.
The last "job" send `descriptive-beast` never finished, while it should have timed out after 5 minutes.

**Comment by azawlocki** [comment]
@maaktweluit @mfranciszkiewicz `descriptive-beast` is the same provider that was causing problems in https://github.com/golemfactory/yapapi/issues/441. 

The timeout for a single task in `blender.py` is not 5 minutes but 10 minutes, to take into account the time required to download a VM image on a provider where it's not present -- 5 minutes that we used to have was often not enough. And the requestor was interrupted before this time, so I can't see any issues here (other than that already reported in https://github.com/golemfactory/yapapi/issues/441).

**Comment by tworec** [comment]
I agree with @azawlocki
We can think of some improvements for the current strategy, but what is described as an issue here is correct in the current state of high-level APIs.
