### ISSUE TITLE
yapapi didn't get invoices before it finished 

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna-triage#133]
(first log file) (devnet-beta.2 erc20)
yagna version: v0.7.1-rc1 
OS+lang+version (if applicable): win yapapi

```
[2021-06-22T12:15:49.278+0200 INFO yapapi.executor] 3 agreements still unpaid, waiting for invoices...


...


[2021-06-22T12:16:19.272+0200 WARNING yapapi.executor] Unpaid agreements: {'d9155f10cf0766df21c7fadb0c54921a9f1bb8ed8fa285528c12a1ab3a751b0b', 'd4fdbf2e6bd37d433cd093729fa54da09dc09b2f84c8a3a8ea2899aaa2b7456f', '7e7704e3c5e1ae82124bc898d0d6f1953b89ff7407299df692d0f3b31a117cf2'}
```

[blender-yapapi-2021-06-22_12.15.15.log](https://github.com/golemfactory/yagna-triage/files/6693597/blender-yapapi-2021-06-22_12.15.15.log)
[blender-yapapi-2021-06-22_12.21.13.log](https://github.com/golemfactory/yagna-triage/files/6693604/blender-yapapi-2021-06-22_12.21.13.log)
[blender-yapapi-2021-06-22_12.21.13.log](https://github.com/golemfactory/yagna-triage/files/6693605/blender-yapapi-2021-06-22_12.21.13.log)
[data.zip](https://github.com/golemfactory/yagna-triage/files/6693607/data.zip)

blue's logs:
[yajsapi-2021-06-22_12-25-03.log](https://github.com/golemfactory/yagna-triage/files/6693676/yajsapi-2021-06-22_12-25-03.log)
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/6693677/yagna_rCURRENT.log)

**Comment by maaktweluit** [comment]
it seems the invoices are send 10-30 seconds after the api gives up..

I think the API could wait longer or the invoice needs to be retried sooner

**Comment by jiivan** [comment]
Maybe it's not necessary to wait until activities are finished (if agreement is already closed)

https://github.com/golemfactory/yagna/blob/4b5e9d05ac7ce1f2d53adf1659476c6acabde282/agent/provider/src/payments/payments.rs#L650-L651

Provider doesn't have much time to issue invoice as yapapi only waits 30 seconds:
https://github.com/golemfactory/yapapi/blob/86e615d2723b5e27dcc9be811909cc038c8fa1cc/yapapi/engine.py#L298-L301

**Comment by nieznanysprawiciel** [comment]
@jiivan Provider must wait for activities, because before sending last Debit Note and Invoice, he need to compute final amount of money to be paid.
Are you suggesting, that this is the point, where the delay happens?

**Comment by nieznanysprawiciel** [comment]
We decided to adjust Provider to make 5 Invoice resents in first 30 seconds
