### ISSUE TITLE
yapapi - Task was destroyed but it is pending

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#15]
Asignee: Artur Zawłocki
Reporter: ederenn

ederenn - Win 10+py -`Task was destroyed but it is pending!` after finishing blender example on python in yapapi task finishes but gives: "Task was destroyed but it is pending!" (Python version 3.8p.6)

```jsx
[2020-11-25 12:56:58,702 INFO yapapi.summary] Executor shut down
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<AsyncWrapper._worker() running at C:\Users\ederenn\.envs\yagna-python-tutorial\lib\site-packages\yapapi\executor\utils.py:34> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x00000118394DCC10>()]>>
```

**Comment by azawlocki** [comment]
This issue should be fixed by https://github.com/golemfactory/yapapi/pull/228
