### ISSUE TITLE
goerli shown on network list in golemsp status

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#171]
Name: ederenn
  
  if it is a new network, and we are able to use it, should be mentioned in the papers (and maybe in the blogpost)
    if we are not planning to share info about it, it should be hidden on the list
  
  ```
    network               mumbai                        │
    │  amount (total)        1099.924860558341997779 tGLM  │
    │      (goerli)          0 tGLM                        │
    │      (mumbai)          0 tGLM                        │
    │      (rinkeby)         1000.006753314891127779 tGLM  │
    │      (zksync)          99.91810724345087 tGLM        │
    │                                                      │
    │  pending               0 tGLM (0)                    │
    │  issued                0 tGLM (0)
    ```

**Comment by tworec** [comment]
I'd recommend removing it, because when one will do
```
yagna payment init --sender --network goerli --driver zksync
```
yagna panics
```
[2021-12-01T17:01:03.917+0100 DEBUG ya_zksync_driver::driver] init: Init { address: "0x4c94f8883553ed92f7cffb01eab9968152291027", network: Some("goerli"), token: None, mode: SEND }
[2021-12-01T17:01:03.917+0100 DEBUG ya_zksync_driver::zksync::wallet] init_wallet. msg=Init { address: "0x4c94f8883553ed92f7cffb01eab9968152291027", network: Some("goerli"), token: None, mode: SEND }
[2021-12-01T17:01:03.917+0100 DEBUG ya_zksync_driver::zksync::wallet] get_wallet "0x4c94f8883553ed92f7cffb01eab9968152291027"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "goerli"',
```

**Comment by jiivan** [comment]
> I'd recommend removing it, because when one will do
> 
> ```
> yagna payment init --sender --network goerli --driver zksync
> ```
> 
> yagna panics

golemsp never asks yagna for such a thing:

https://github.com/golemfactory/yagna/blob/d7480f52369b3b4bee0ea4abc07e538b55251b8c/golem_cli/src/command/yagna.rs#L271-L272

Altough maybe yagna's payment shouldn't panic in this situation (a task for another issue).

My conclusion is that:

 1. golemsp won't cause such problem, because he has internal list of zksync compatible networks (`command::yagna::ZKSYNC_DRIVER`)
 2. yagna payment panics every time you try to initialize it with zkSync and incompatible network (polygon/mumbai/goerli)
 3. This issue is payment related (not provider)
 4. If we don't want to show goerli than IMHO it should be removed from core model: https://github.com/golemfactory/yagna/blob/d7480f52369b3b4bee0ea4abc07e538b55251b8c/core/model/src/payment.rs#L443-L444

**Comment by tworec** [comment]
yes, all the above is right.

I'd remove `goerli` entirely from the yagna codebase, including `golemsp` as per this issue.

I'd also fill an issue to fix panicking zksync payment driver, to be fixed later on (eg. in patch release)

**Comment by tworec** [comment]
I think this is also for the patch release. No need to be fixed immediately.

**Comment by jiivan** [comment]
> I'd also fill an issue to fix panicking zksync payment driver, to be fixed later on (eg. in patch release)

I've created an issue: https://github.com/golemfactory/yagna/issues/1740

**Comment by maaktweluit** [comment]
This will remove the option to test enter / exit from mumbai, asked 2rec about this

**Comment by maaktweluit** [comment]
@tworec what was the final descision on enter / exit? will we keep goerli?

**Comment by tworec** [comment]
Together with @prekucki we've decided to support and keep `goerli`.
In order to do that we need:
- check all yagna CLI to support `goerli` --> @nieznanysprawiciel / @golemfactory/core 
  - fix golemfactory/yagna#1740
- enrich handbook to mention it --> @shadeofblue / @golemfactory/ya-sdk

**Comment by jiivan** [comment]
Core team has created two issues related to this:
 - https://github.com/golemfactory/yagna/issues/1803
 - https://github.com/golemfactory/yagna/issues/1740
 
Leaving the handbook enrichment & verifying ya*api compatibility to @golemfactory/ya-sdk

**Comment by golmek** [comment]
Closing ticket as Goerli is part of default network since YAGNA 0.12.2
