### ISSUE TITLE
golemsp status displays an ugly error when yagna is running without a provider agent

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#173]
why
- when nothing is running golemsp status show a neat table
- when yagna is running, golemsp status shows an error

what
- think about what to do
- comment on this task
- refine again next session

Name: blue
OS+lang+version (if applicable): linux / provider

```
$ yagna service run

# then on another console

$ golemsp status                                                                                                                                                     
[2021-12-01T11:29:21Z ERROR golemsp] Provider is not functioning properly. No offers Subscribed.
```

The expectation would be to display the proper status, just saying "provider is not running"

**Comment by tworec** [comment]
This is a very low priority.

Also the proposition is not good, since the provider can be running but not properly configured.


Pls came up with more appropriate msg eg. `No offers Subscribed. Please make sure your Provider is running and properly configured. `

**Comment by maaktweluit** [comment]
In refinement we discussed:
- we put this after the 0.10.0 code freeze priority wise
- we will think about the best ways to resolve this and comment on this issue before then

**Comment by nieznanysprawiciel** [comment]
Low priority and impact. Closing
