### ISSUE TITLE
ERC-20 rinkeby gas too high

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#175]
yagna version: rc-06
OS+lang+version (if applicable): everywhere
Title: ERC-20 transactions on rinkeby are send with 30 GWEI while it should be 1 GWEI

**Comment by shadeofblue** [comment]
@nieznanysprawiciel can this one be closed?

**Comment by golmek** [comment]
Closing the ticket as it is hard to analyse after such a long time, different YAGNA and different Network conditions, there is also no logs.
