### ISSUE TITLE
Transaction confirmations not printed out

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#176]
Name: Transaction confirmations not printed out
yagna version: rc-06
OS+lang+version (if applicable): everywhere
Title: Transaction confirmations were not printed out after running out of funds for gas and re-funding the account

```
Missing `Transaction confirmed and succeeded` for the failed transactions
although the transactions went through.

last tx error log @ 2021-12-02T12:57:12.189+0100
```
[yagna_rCURRENT.log.tar.gz](https://github.com/golemfactory/yagna-triage/files/7641987/yagna_rCURRENT.log.tar.gz)

**Comment by shadeofblue** [comment]
@nieznanysprawiciel ?

**Comment by golmek** [comment]
Closing ticket as nothing happened over 1.5 year and there is already new YAGNA.
