### ISSUE TITLE
Scamming providers by setting a too low budget doesn't accurate say which funds are missing on Polygon. Is it MATIC, GLM or both?

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#178]
Name: **Scamming providers by setting a too low budget doesn't accurate say which funds are missing on Polygon. Is it MATIC, GLM or both?**
yagna version: rc6
OS+lang+version:  everywhere

> [2021-12-02T12:29:12.351+0100 ERROR yapapi.summary] [Job 1] Failed to accept an invoice or a debit note from 'ProviderInfo(id='0x40c6b08d3f4b3badec5f8a1844acfb4f7b101cd9', name='red-coat', subnet_tag='testnet')', reason: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Content-Length': '166', 'Content-Type': 'application/json', 'Date': 'Thu, 02 Dec 2021 11:29:12 GMT')>
HTTP response body: {"message":"Not enough funds. Allocated: 0.00000000000099999999999999997988664762925561536725284350612952266601496376097202301025390625 Needed: 0.001483339991633333"}
>

**Comment by shadeofblue** [comment]
@nieznanysprawiciel could you triage this issue?

**Comment by golmek** [comment]
Allocation is always done in GLM. Consequently it cannot be connected with MATIC/ETH...

Closing this ticket
