### ISSUE TITLE
problems with graceful shutdown on http example

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#180]
Name: ederenn
yagna version: 0.9.0
OS+lang+version (if applicable): windows, py
!!! attach `blender-yapapi.log`, zipped data-dir !!!

it got stuck on stopping, second ctrl c was needed
(might be related to handshake error with one of the nodes, or the other provider  being stopped by owner during connection with my node)
    
    ```
    Shutting down gracefully, please wait a short while or press Ctrl+C to exit immediately...
    ^CUnclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x0000021E989B9190>
    HTTP server stopped
    ['crownstar: running', 'red-coat: running']
    ['crownstar: stopping', 'red-coat: stopping']
    ['crownstar: stopping', 'red-coat: stopping']
    
    C:\Users\ederenn\yapapi\examples\http-proxy>
    ```

**Comment by shadeofblue** [comment]
again, @ederenn no logs...
