### ISSUE TITLE
hyperlink does not work in handbook

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#212]
Name: Wojtek

[https://github.com/golemfactory/yagna-docs/blob/develop/payments/using-golem-on-mainnet/layer-2-payments.md](https://github.com/golemfactory/yagna-docs/blob/develop/payments/using-golem-on-mainnet/layer-2-payments.md) → hyperlink does not work in handbook [https://golem-network.gitbook.io/golem-sdk-develop/payments/using-golem-on-mainnet](https://golem-network.gitbook.io/golem-sdk-develop/payments/using-golem-on-mainnet)

**Comment by tworec** [comment]
duplicate of https://github.com/golemfactory/yagna-docs/issues/107
