### ISSUE TITLE
yagna did a DoS on testnet geth

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna-triage#217]
Nginx requests received by our testnet geth: 
![nginx_requests](https://user-images.githubusercontent.com/220752/167611973-82dbe3b1-3045-4d1a-80c6-04b907ebc5e9.png)

It was caused by a checker running in the testnet subnet. Here's a copy of whole datadir (with databases and logs): https://drive.google.com/file/d/1lciB-pffjX_Q6PQSf7H6cAIhf3Gz9ERg/view?usp=sharing

It has tons of errors

```
ERROR ya_erc20_driver::erc20::wallet] Error sending transaction: GenericError { inner: "RPC error: Error { code: ServerError(-32000), message: \"insufficient funds for gas * price + value\", data: None }" }
```
and
```
INFO  ya_erc20_driver::driver::cron] Transaction not found on chain
```

**Comment by etam** [comment]
When trying to restart checker, I found that during `payment fund` it could send a tx that was rejected by geth. Later attempts to run `payment fund` were causing a line in logs "Already pending a mint transactin.".

**Comment by johny-b** [comment]
I've seen this once or twice last week (i.e. I've seen the error messages, I don't know about `geth` requests) so I'm not super-sure about `impact: low`.

I'll tell you if I see this again.

**Comment by nieznanysprawiciel** [comment]
@scx1332 is working on new payment driver implementation.
It is not worth investigating it, if the problem won't occur after introducing changes
