### ISSUE TITLE
mumbai transaction confirmed, but resulted in error

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#220]
Name: blue
OS+lang+version (if applicable): mac

    
 ```
    Transaction confirmed, but resulted in error
 ```
    
 on [mumbai.polygonscan.com](http://mumbai.polygonscan.com/):
    
 [https://mumbai.polygonscan.com/tx/0x0888e83ff3e2655f7c39319c54847cd5786266079307fbf129a0be184e287e9b](https://mumbai.polygonscan.com/tx/0x0888e83ff3e2655f7c39319c54847cd5786266079307fbf129a0be184e287e9b)
    
AND upload full logs here:
[yagna_rCURRENT (6).log](https://github.com/golemfactory/yagna-triage/files/8813627/yagna_rCURRENT.6.log)

**Comment by scx1332** [comment]
Gas limit too low:

fixed in https://github.com/golemfactory/yagna/pull/2012/files

please review
