### ISSUE TITLE
rinkeby zksync has been terminated

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna-triage#225]
Why: zkSync removed support for rinkeby and migrated to goerli. It causes `golemsp status` to wait more than 1 minute before printing anything.

What:
remove zksync forever?
Remove zkSync from golemsp testnet list.
Ask Reqc about next steps
 - [ ] Remove faucet
 - [ ] domain rinkeby-api.zksync.golem.network
 - [ ] Look for other services with rinkeby zksync to remove

**Comment by nieznanysprawiciel** [comment]
First step is removing zksync from community hybrid NET release:
https://github.com/golemfactory/yagna/issues/2192

**Comment by EvilSeeQu-sys** [comment]
Move to goerli ?

**Comment by jiivan** [comment]
https://github.com/golemfactory/golem-internal/issues/526
