### ISSUE TITLE
`golemsp status` doesn’t give any hint on whether we’re using the old or the new network driver

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna-triage#240]
version: linux+yagna 0.12.0-rc4 (37539868 2022-11-09 build #239)

the user has no idea whether they're running `hybrid` or `central`

(of course, they shouldn't be aware of the names but it would be good if they could easily confirm the correct driver without having to look at the head of the logs)

**Comment by nieznanysprawiciel** [comment]
Outdated.
Central Net shouldn't be used anymore
