### ISSUE TITLE
Only one payment other payments are not done

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#46]
mdt - MacOS+js+0.3.0-alpha.3  - Only one payment other payments are not done.

[yagna_rCURRENT.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a774c3ed-9c5b-46be-8c7f-bdaa8eb5c53b/yagna_rCURRENT.log)

[yajsapi-2021-01-28T12:41:52+01:00.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/82c78acf-3879-4918-a543-4795bfada7c2/yajsapi-2021-01-28T1241520100.log)

**Comment by maaktweluit** [comment]
Will be fixed by https://github.com/golemfactory/yagna/pull/982

**Comment by mateuszsrebrny** [comment]
not seen for a couiple sessions - closing
