### ISSUE TITLE
yajsapi - sending 0 invoices

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#51]

**Comment by filipgolem** [comment]
Please provide more details or close this issue. The provider (not the requestor) is sending invoices, `yajsapi` correctly accepts them.

**Comment by maaktweluit** [comment]
Yes, we can close this issue:
- it is OK for a provider to send 0 invoice
- requestor api should accept it
- payment service should mark them as settled ( WIP )
