### ISSUE TITLE
windows coloring is not working always 

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#55]
Mateusz win+py - windows coloring is not working for versions at the beginning of the output. it works later for coloring the outputs to cyan.

```
yapapi version: ←[33;1m0.5.0a3←[0m
```

**Comment by azawlocki** [comment]
Note: the difference between the version number and the output in cyan is that the former is printed to `stderr` and the latter to `stdout`.

**Comment by azawlocki** [comment]
Note to self: use https://pypi.org/project/colorama/
