### ISSUE TITLE
not talking to all nodes

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#57]
blue - macos mojave+JS+0.3.0-alpha.6 - yajsapi waited for the cheapest node (the lenny face 2rec) to free before it even started speaking to the others and only after that one responded it sent several tasks to others

[yagna_rCURRENT.txt](https://github.com/golemfactory/yagna-triage/files/5951246/yagna_rCURRENT.txt)
[yajsapi-output.txt](https://github.com/golemfactory/yagna-triage/files/5951248/yajsapi-output.txt)

**Comment by tworec** [comment]
@shadeofblue pls take a look at attached (by you) `yajsapi` output and you'll see that Proposals are appearing steadily.
So Market is propagating offers properly. It is `yajsapi` who decides not to propose agreements to any1 beside best (highest score) Provider which happened to be my host (lenny face). 

Search for `Agreement proposed` string within `yajsapi` output and you will easily notice it. So it is a characteristic of `yajsapi` and if you find it to be a bug, than you know what to do :)

**Comment by shadeofblue** [comment]
unsure if it's a bug but I do find it strange and indeed, would have expected the requestor to use other providers if the one I had chosen isn't responding

**Comment by filipgolem** [comment]
This is the default algorithm in both `yapapi` and `yajsapi`.
In the beta release there will be a new `DecreaseScoreForUnconfirmedAgreement` strategy which should decrease scores for offers from providers which failed to approve the agreement. Also, the timeouts were decreased - it should partly fix this problem.

**Comment by tworec** [comment]
So, we should close it probably...
