### ISSUE TITLE
{ code: 20, error: "unable to get local issuer certificate" }

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna-triage#87]
Discord user had issues trying to run any command related to being a provider. Each command would lead to an error like this:

`Error: Library error: Api(Transport("hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1913 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" }))"))`

Seems like an issue with Rust not being able to find the ca bundle, so passing the path to the `SSL_CERT_FILE` var fixed the issue.

**Fix:**
`SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt golemsp status`

**Comment by cryptobench** [comment]
Not sure if this is something you want to investigate or not, but just reporting it in case it comes up in the future.

So far i've only seen it once since our first ever release.

**Comment by cryptobench** [comment]
This one has begun popping up a fair bit now. Not much but more than normal.

**Comment by etam** [comment]
Seems like a problem with https://github.com/alexcrichton/openssl-probe. We might need to update to latest release.
Adding to Core board.

**Comment by cryptobench** [comment]
Request from @etam:

> Additional question: do they have a file /etc/pki/tls/certs/ca-bundle.crt or is it somewhere else? For example on my openSUSE it's /etc/ssl/ca-bundle.pem. 
> Helpful command: find /etc -name 'ca-bundle.*'
> 

This guy is on Ubuntu 20.04.2 LTS

```
ebt@ebt-ProLiant-DL380p-Gen8:~$ sudo find /etc -name 'ca-bundle.'
ebt@ebt-ProLiant-DL380p-Gen8:~$ find /etc -name 'ca-bundle.'
find: ‘/etc/ssl/private’: Permission denied
find: ‘/etc/cups/ssl’: Permission denied
find: ‘/etc/polkit-1/localauthority’: Permission denied
ebt@ebt-ProLiant-DL380p-Gen8:~$ sudo find /etc -name 'ca-bundle.*'
ebt@ebt-ProLiant-DL380p-Gen8:~$
```

This is the linux mint guy (Linux Mint 19.2 Cinnamon)
 
```
find /etc -name 'ca-bundle.*'
find: ‘/etc/polkit-1/localauthority’: Permission denied
find: ‘/etc/ssl/private’: Permission denied
find: ‘/etc/cups/ssl’: Permission denied
```

**Comment by nieznanysprawiciel** [comment]
It seems to be the problem with yagna dependency `hyper`. Probably it will disappear after upgrade.
Since it has minor severity and impact, and you provided workaournd for this problem, we aren't going to pick up this task in the nearest future.

**Comment by cryptobench** [comment]
![image](https://user-images.githubusercontent.com/33448819/130923119-dc4b0360-bf4c-4249-a261-9af66b7ad745.png)
 
 Fresh ubuntu machine on bare metal. It seems to just be metrics pushing that's having issues though.
 
 When is the upgrade expected @nieznanysprawiciel ?

**Comment by nieznanysprawiciel** [comment]
@cryptobench Update is not planned at this moment. Please inform users about the workaround, that you mentioned

**Comment by cryptobench** [comment]
Okay, was just interested in knowing if Hyper will get upgraded in the 0.8.0 or another release.

Users has already been informed but the workaround is not guaranteed to fix the issue.

**Comment by cryptobench** [comment]
This issue has started popping more and more up over time. It doesn't break yagna or anything, but users are wondering why their stats on the stats page aren't matching their `golemsp status` window

**Comment by maaktweluit** [comment]
we should try to add paths to the searching of the certificate bundle.

Maybe @prekucki already has a fix on the miner branch?

**Comment by cryptobench** [comment]
Bumping this issue as it's pretty common nowadays. Users are relying on the stats page for data and it might show incorrect metrics because of this issue, which is devaluing the stats page a fair bit.

**Comment by nzmel** [comment]
The community is seriously concerned with this issue

**Comment by tworec** [comment]
@nieznanysprawiciel pls make a triage for this issue
Probably related one https://github.com/golemfactory/yagna/issues/1586

**Comment by nieznanysprawiciel** [comment]
> @nieznanysprawiciel pls make a triage for this issue Probably related one [golemfactory/yagna#1586](https://github.com/golemfactory/yagna/issues/1586)

We are going to implement simple workaround: https://github.com/golemfactory/yagna/issues/1911
since target solution (https://github.com/golemfactory/yagna/issues/1714) is more complicated

**Comment by tworec** [comment]
@nieznanysprawiciel pls transfer this issue and link the respective PR to it.
Also, add a proper tag to denote within which release (patch) users will have it fixed.
